services:
  - docker

before_install:
- docker pull jyjiang/latex-paper-build

script:
- docker run -ti -v ${PWD}:/paper:Z jyjiang/latex-paper-build bash -c "cd /paper; make clean;make"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN
  keey_history: true
  on:
    branch: master
