name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: pull images
        run: |
          docker pull jyjiang/latex-paper-build:latest
      - name: compile latex
        run: git submodule init && git submodule update; make clean; make docker
      - name: deploy to pages
        run: |
          rm *.tex; rm -rf .git
          rm .gitignore; git init
          git config user.name "Deploy"
          git config user.email "deploy@github.com"
          git add paper.pdf; git commit -m "deploy"
          URL=$(git remote get-url origin | sed -s 's/https:\/\///g')
          git push --force https://$TOKEN@$URL master:gh-pages
